### ISSUE TITLE
Eagle 2 layer DRU issue - might just be description but not sure?

### ISSUE THREAD

**Issue by KevWal** [jonnew/jonnew-lbr#8]
Hi

The file https://github.com/jonnew/jonnew-lbr/blob/master/eagle/dru/jlcpcb-2-layer.dru has a description:

description[en] = <b>JLCPCB  4-layer Design Rules</b>\n<p>\nJLC7628 Stackup\n

Which is clearly incorrect, is it just the description that is incorrect?

Thanks.

**Comment by jonnew** [comment]
Yep, almost certainly. Feel free to edit.
